{ "name":"espresso", "espresso": 1, "recipie":["Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam aliquam, lectus ut posuere accumsan, tellus enim sollicitudin elit, eget facilisis dolor dui vitae ante. ", "Etiam aliquam, lectus ut posuere accumsan, tellus enim sollicitudin elit, eget facilisis dolor dui vitae ante."], "capacity": 90}
{ "name":"espresso doppio", "espresso": 2, "recipie":["In hac habitasse platea dictumst. Ut molestie sapien vitae lacus pulvinar bibendum. ", "Etiam aliquam, lectus ut posuere accumsan, tellus enim sollicitudin elit, eget facilisis dolor dui vitae ante."], "capacity": 90} 
{ "name":"espresso romano", "espresso":1, "addons": [{"name":"lemon", "amount":"1 plaster"}], "recipie":["Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam aliquam, lectus ut posuere accumsan, tellus enim sollicitudin elit, eget facilisis dolor dui vitae ante. ", "Etiam aliquam, lectus ut posuere accumsan, tellus enim sollicitudin elit, eget facilisis dolor dui vitae ante."], "capacity": 90}
{ "name":"espresso con panna", "espresso":1, "addons": [{"name":"cream", "amount":"1 pełna łyżka"}], "recipie":["Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam aliquam, lectus ut posuere accumsan, tellus enim sollicitudin elit, eget facilisis dolor dui vitae ante. ", "Etiam aliquam, lectus ut posuere accumsan, tellus enim sollicitudin elit, eget facilisis dolor dui vitae ante."], "capacity": 90}
{ "name":"espresso macchiato", "espresso":1, "addons": [{"name":"foam", "amount":"1-2 łyżeczki"}], "recipie":["Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam aliquam, lectus ut posuere accumsan, tellus enim sollicitudin elit, eget facilisis dolor dui vitae ante. ", "Etiam aliquam, lectus ut posuere accumsan, tellus enim sollicitudin elit, eget facilisis dolor dui vitae ante."], "capacity": 90}
{ "name":"espresso affogato", "espresso":1, "addons": [{"name":"icecream", "amount":"1 gałka"}], "recipie":["Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam aliquam, lectus ut posuere accumsan, tellus enim sollicitudin elit, eget facilisis dolor dui vitae ante. ", "Etiam aliquam, lectus ut posuere accumsan, tellus enim sollicitudin elit, eget facilisis dolor dui vitae ante."], "capacity": 90}
{ "name":"piccolo latte", "espresso":1, "addons": [{"name":"foam", "amount":"40ml"}], "recipie":["Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam aliquam, lectus ut posuere accumsan, tellus enim sollicitudin elit, eget facilisis dolor dui vitae ante. ", "Etiam aliquam, lectus ut posuere accumsan, tellus enim sollicitudin elit, eget facilisis dolor dui vitae ante."], "capacity": 90}
{ "name":"caffe americano", "espresso":2, "addons": [{"name":"hotwater", "amount":"90ml"}], "recipie":["Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam aliquam, lectus ut posuere accumsan, tellus enim sollicitudin elit, eget facilisis dolor dui vitae ante. ", "Etiam aliquam, lectus ut posuere accumsan, tellus enim sollicitudin elit, eget facilisis dolor dui vitae ante."], "capacity": 160}
{ "name":"cafe au lait", "espresso":1, "addons": [{"name":"hotmilk", "amount":"60ml"}], "recipie":["Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam aliquam, lectus ut posuere accumsan, tellus enim sollicitudin elit, eget facilisis dolor dui vitae ante. ", "Etiam aliquam, lectus ut posuere accumsan, tellus enim sollicitudin elit, eget facilisis dolor dui vitae ante."], "capacity": 145} 
{ "name":"cappuccino", "espresso":1, "addons": [{"name":"steamedmilk", "amount":"40ml"}, {"name":"foam", "amount":"40ml"}], "recipie":["Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam aliquam, lectus ut posuere accumsan, tellus enim sollicitudin elit, eget facilisis dolor dui vitae ante. ", "Etiam aliquam, lectus ut posuere accumsan, tellus enim sollicitudin elit, eget facilisis dolor dui vitae ante."], "capacity": 145}
{ "name":"caffe latte macchiato", "espresso":1, "addons": [{"name":"steamedmilk", "amount":"60ml"}, {"name":"foam", "amount":"60ml"}], "recipie":["Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam aliquam, lectus ut posuere accumsan, tellus enim sollicitudin elit, eget facilisis dolor dui vitae ante. ", "Etiam aliquam, lectus ut posuere accumsan, tellus enim sollicitudin elit, eget facilisis dolor dui vitae ante."], "capacity": 160}
{ "name":"caffe latte macchiato smakowa", "espresso":1, "addons": [{"name":"steamedmilk", "amount":"50ml"}, {"name":"foam", "amount":"50ml"}, {"name":"syrop", "amount":"30ml"} ], "recipie":["Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam aliquam, lectus ut posuere accumsan, tellus enim sollicitudin elit, eget facilisis dolor dui vitae ante. ", "Etiam aliquam, lectus ut posuere accumsan, tellus enim sollicitudin elit, eget facilisis dolor dui vitae ante."], "capacity": 160}
{ "name":"mocha", "espresso":1, "addons": [{"name":"steamedmilk", "amount":"50ml"}, {"name":"foam", "amount":"50ml"}, {"name":"chocosyrop", "amount":"30ml"}], "recipie":["Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam aliquam, lectus ut posuere accumsan, tellus enim sollicitudin elit, eget facilisis dolor dui vitae ante. ", "Etiam aliquam, lectus ut posuere accumsan, tellus enim sollicitudin elit, eget facilisis dolor dui vitae ante."], "capacity": 160}
{ "name":"irish coffee", "espresso":1, "addons": [{"name":"cream", "amount":"100ml"}, {"name":"whisky", "amount":"30ml"}], "recipie":["Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam aliquam, lectus ut posuere accumsan, tellus enim sollicitudin elit, eget facilisis dolor dui vitae ante. ", "Etiam aliquam, lectus ut posuere accumsan, tellus enim sollicitudin elit, eget facilisis dolor dui vitae ante."], "capacity": 160}


